### PR TITLE
thuang-create-collection-integration

### LINKED ISSUE #663: FE/BE Integration
This ticket is for making sure Create Collection flow is integrated properly end to end between BE and FE

### PR DESCRIPTION
**Pull request by tihuan**
1. Updates collection link object keys to add `link_` prefix
1. Adds link name display support to fall back to showing the URL host when `link_name` is not available.
1. Create collection flow now works end to end!

QA Steps:
1. Pull the branch `thuang-create-collection-integration`
1. Make sure your `frontend/src/configs/configs.js` points to Dev: `API_URL: "https://api.cellxgene.dev.single-cell.czi.technology",`
1. Make sure you use Requestly Chrome Extension to hard code your `cxguser` and `session` cookies from Dev env
1. Fire up `npm start`
1. Navigate to `http://localhost:8000/?auth=true&cc=true`
1. Click on "Create Collection" button
1. Fill in the form
1. Click "Create"
1. You should now land on your newly created private collection page!

NOTE: You might be able to get this to work via `make local-init` and `make local-start`, but I haven't tested that yet lol

Screenshot below simulates the case what users will see when `link_name` is not available!
Screen Shot 2020-11-13 at 1 11 30 PM

demo

PTAL thank you!

resolves #663

### CODE REVIEW

**Review by Bento007 — APPROVED** [review]
LGTM

**Comment by tihuan** [comment]
@hthomas-czi I merged this PR for now, since it's blocking @seve ! Please let me know your feedback and I'll address them as a separate PR! Thank you!

**Comment by hthomas-czi** [comment]
@tihuan Sorry I missed this! 🤦 

Quick question, where is the blue fill in the text field coming from?

**Comment by tihuan** [comment]
OH! I think that's a Chrome thing, which indicates the field is autocompleted from the autofill click I did!

**Comment by hthomas-czi** [comment]
Aha! Good call. Overall it looks great! The only issue I see is the `Add Link` button isn't left-aligned, but I understand it's because of the hover state. We may want to create our own "link-style" button. What do you think?

**Comment by tihuan** [comment]
Yeah the hover state highlight seems to need the padding, thus causing the visual misalignment 😆 Not sure how Blueprint intends to left align stuff with that design 🤔 

Maybe using `outlined` instead of `minimal`? Our own custom "link-style" button would work too!

**`minimal`:**
Screen Shot 2020-11-18 at 9 25 42 PM


**`outlined`:**
Screen Shot 2020-11-18 at 9 24 25 PM

**Comment by hthomas-czi** [comment]
@tihuan Good idea! I like that solution.

**Comment by tihuan** [comment]
@hthomas-czi YAY! OK thanks! I'll add the change in the policy PR 😆

**Pull request merged**
