### PR TITLE
Small fix for Dataset.create

### PR DESCRIPTION
**Pull request by mckinsel**
You can't give it a list, uselist=False

### CODE REVIEW

**Review by maniarathi — APPROVED** [review]
LGTM -- one question, is there a way to create a negative test for this to prevent the bug in the future?

**Comment by mckinsel** [comment]
Yeah there should be...I'm a little confused about why the existing tests didn't catch it.

**Comment by tihuan** [comment]
@mckinsel is there a ticket that this PR can attach to or is this just a general quick fix? Thank you!

**Comment by mckinsel** [comment]
@tihuan just a quick fix. It arose during adding some new datasets.

**Comment by tihuan** [comment]
Got it! Thanks so much for the PR, @mckinsel 🎉 🤩

**Comment by mckinsel** [comment]
Pretty sure this was fixed by #741

**Pull request closed without merging**
