### PR TITLE
thuang-disable-create-collection-autocomplete

### PR DESCRIPTION
**Pull request by tihuan**
https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/corpora-data-portal/988

#988 

### Reviewers
**Functional:** 
@seve 

**Readability:** 
@MDunitz 

---

## Changes
- add
- remove
- modify

## Definition of Done (from ticket)
The form should no longer provide autocomplete suggestion for any field!

Screen Shot 2021-03-31 at 4 57 20 PM

### CODE REVIEW

**Review by MDunitz — APPROVED** [review]
lgtm

**Comment by tihuan** [comment]
Thanks so much, @MDunitz ! Mergingg

**Comment by maniarathi** [comment]
Hey @tihuan this doesn't actually work in Chrome unfortunately :( .. I did a tiny bit of research into this and it seem to be a persistent problem: https://stackoverflow.com/questions/12374442/chrome-ignores-autocomplete-off. Just an FYI.. I will check in with Brian to see if we want to still tackle this or accept it as a bug.

Quick question though -- do you have a quick resource on how to tackle _accepting_ auto complete info?

**Comment by tihuan** [comment]
Ah thanks for catching this, @maniarathi ! Looks like form level `autocomplete="off"` was not enough 🤦 

I did some more research and found another solution suggested in 2021 by someone on Stackoverflow:

https://github.com/chanzuckerberg/corpora-data-portal/pull/1073

Seems to be working better now! PTAL! Thank you!

**Pull request merged**
