### PR TITLE
Add a new job to github actions after deploy to run a smoke test.

### PR DESCRIPTION
**Pull request by bmccandless**
Note:  this is currently only done after a dev deploy.  It could
be added to staging and prod as well.

 #778

#### Reviewers
**Functional:**  @Bento007 

**Readability:**  @tihuan 

---

## Changes
- add
- remove
- modify

### CODE REVIEW

**Comment by tihuan** [comment]
Thanks so much for adding this, @bmccandless 😄 🙏 ! 

I'm assuming we want to run smoke test against the real prod on `cellxgene.cziscience.com`? If so, I created a [PR](https://github.com/chanzuckerberg/corpora-data-portal/pull/831) to update the command to do so! Thank you!

**Review by tihuan — APPROVED** [review]
LGTM after merging https://github.com/chanzuckerberg/corpora-data-portal/pull/831 🙏 

Thanks so much again, @bmccandless 🚀 !

**Review by Bento007 — APPROVED** [review]
As long as the smoke tests currently pass I approve

**Comment by bmccandless** [comment]
Hi @tihuan , there are three deploy scripts:  deploy, deploy-staging, and deploy-prod.  deploy is for the dev deployment.   I don't think we want e2e-prod here since it would basically be the dev e2e tests running against the prod deployment, which might not be up to date.  But, also I'm not super familiar with these scripts, so please correct me if I'm wrong.

**Comment by tihuan** [comment]
Hi @bmccandless ! Ooh I see! So we want to run E2E against `https://cellxgene.dev.single-cell.czi.technology` after deploy? 

If so, I will update my PR from `e2e-prod` to `e2e-dev`!

Thank you!

**Comment by tihuan** [comment]
Just updated the [PR](https://github.com/chanzuckerberg/corpora-data-portal/pull/831/files) if that's what we want 😆 🙏 

Thanks again!

**Pull request merged**
