### PR TITLE
thuang-651-part2

### PR DESCRIPTION
**Pull request by tihuan**
Changelog from `thuang-651-part2`:
1. Hard code an existing POST response, since BE endpoint is WIP `frontend/src/common/queries/collections.ts`
1. Code split Create Collection modal's Content component to only download the component when the button is hovered

Changelog from `thuang-651-create-collection-component`:
1. Add `gatsby-plugin-sass` to allow Blueprint.js scss overwrite
1. Add `@blueprintjs/icons`
1. Add `lodash-es` for ES6 module version of lodash, which is tree shaking friendly and, in theory, reduces js bundle size
1. Introduce @hthomas-czi 's design system by adding standardized colors in `frontend/src/components/common/theme.ts` and Blueprint style overwrite in `frontend/src/global.scss`
1. Add `CreateCollectionModal`, which is hidden behind URL param feature flag: `?cc=true` 
1. Build common `Form` components in `frontend/src/components/common/Form`, which allows us to do sync validation and show error when requirement is not met. This includes `Input` and `TextArea` components
1. Add policy attestation where we hard code policy version in the FE

QA steps:
1. Please pull branch `thuang-651-part2`
2. Run `npm i && npm start`
3. Visit: `http://localhost:8000/?cc=true`
4. You should see "Create Collection" button on the upper right corner
5. Play with the form and see if anything is weird for you
6. Currently we hard code POST response to redirect to an existing collection, since BE endpoint is WIP

Form:
Screen Shot 2020-11-04 at 2 42 23 PM

Error state:
Screen Shot 2020-11-04 at 2 41 31 PM

Demo:
gif

Thank you!!

### CODE REVIEW

**Review by hthomas-czi — COMMENTED** [review]
@tihuan What's the logic for triggering the error state?

**Comment by tihuan** [comment]
@hthomas-czi right now error only shows when it's empty for collection name, description, contact name, and contact email

For collection link type and URL, the field will check for empty string, non-URL string, and if it's DOI, it will check for string `"doi.org"` in the link!

**Review by seve — APPROVED** [review]
The 2 commits LGTM!

**Comment by tihuan** [comment]
Thanks @seve ! @hthomas-czi I'll merge this PR into the feature branch and continue the discussion of the form there! Thank you!

**Comment by hthomas-czi** [comment]
@tihuan Does it show the error state if the form field receives focus and then loses focuses while empty? When does the logic first run?

**Pull request merged**
