### PR TITLE
feat: Add PR Linting

### PR DESCRIPTION
**Pull request by seve**
### Reviewers

I'd like all corpora engineers to sign off if possible :)

---

This commit is going to add squash commit naming enforcement.  We're going to follow the [conventional commit standard](https://www.conventionalcommits.org/en/v1.0.0/), with scopes optional for the time being.

Apart from the obvious, this addition is going to require a change in practice when working with PR's with a single commit. Typically, GitHub generates the squash commit message from the PR title. However, when a PR contains a single commit, GitHub instead uses the commit's message as the squash message (see https://github.community/t/how-to-change-the-default-squash-merge-commit-message/1155). In those cases, the linter is going to lint that single commit, asking us to amend the message or add another a commit if it fails the lint.  

This is customizable so if you think we won't forget to edit that default commit message feel free to request it to be turned off.

The action's repo is here: https://github.com/amannn/action-semantic-pull-request

### CODE REVIEW

**Comment by Bento007** [comment]
Update the [contributors.md](https://github.com/chanzuckerberg/corpora-data-portal/blob/main/CONTRIBUTING.md) with links to the convention.

**Comment by seve** [comment]
> Update the [contributors.md](https://github.com/chanzuckerberg/corpora-data-portal/blob/main/CONTRIBUTING.md) with links to the convention and with any other details with what must be done with your PR before it can be merged.

Good idea, done. https://github.com/chanzuckerberg/corpora-data-portal/pull/1150/commits/2fbd6fbcbcede64d6ee98dfc7eb17e88f5847fea

**Review by MDunitz — APPROVED** [review]
lgtm

**Review by tihuan — APPROVED** [review]
LGTM!! More standardization FTW 🚀 !!

**Review by Bento007 — APPROVED** [review]

**Pull request merged**
