### PR TITLE
thuang-fix-fetch-api-cookies PART 2

### PR DESCRIPTION
**Pull request by tihuan**
Part 2 adds `include` to collections related API calls too! Thank you!

### CODE REVIEW

**Comment by tihuan** [comment]
I have a feeling the smoke test is failing right now, because of the `*` for `Access-Control-Allow-Origin` from BE (not verified 😆 ) But @bmccandless is helping us to fix that in this PR!

Thank you!

**Comment by tihuan** [comment]
@bmccandless OH! Sorry I revert it back to `*` 🙏 That was an unintended change 😆 

Also since we actually set `CORS` in `get_chalice_app()` call anyway, I think `CORSConfig()`'s  `allow_origin="*"` will always get overridden by `CORS`?

**Comment by Bento007** [comment]
I don't think we need two CORS configurations. We are already using Chalice CORS, can you use that one or replace it.

**Comment by tihuan** [comment]
@bmccandless @Bento007 PTAL again!

I removed Chalice CORS and used `# pragma: no cover` to ignore the code block 🎉 

Looks like CodeCov uses [`coverage.py`](https://github.com/codecov/example-python) under the hood, and `coverage.py` has a way to exclude code! https://coverage.readthedocs.io/en/coverage-4.3.3/excluding.html

Hopefully it's good to go now! Thank you!

**Comment by bmccandless** [comment]
> @bmccandless @Bento007 PTAL again!
> 
> I removed Chalice CORS and used `# pragma: no cover` to ignore the code block 🎉
> 
> Looks like CodeCov uses [`coverage.py`](https://github.com/codecov/example-python) under the hood, and `coverage.py` has a way to exclude code! https://coverage.readthedocs.io/en/coverage-4.3.3/excluding.html
> 
> Hopefully it's good to go now! Thank you!

Thanks, good to know about "no cover"

**Review by bmccandless — APPROVED** [review]
LGTM

**Comment by tihuan** [comment]
Yay! Thanks for the quick review, @bmccandless 🙏 Added auto merge 🚀 Have a wonderful evening!

**Review by Bento007 — APPROVED** [review]
LGTM

**Pull request merged**
