### PR TITLE
thuang-747-fix-tos-privacy-pages

### LINKED ISSUE #747: Fix cellxgene Terms of Service and Privacy Pages
Currently those two pages are not working in all three environments, especially prod:

https://cellxgene.cziscience.com/static/cellxgene/deploy/tos.html
https://cellxgene.cziscience.com/static/cellxgene/deploy/privacy.html

So the remedy is to host those two pages on Data Portal!

What:

1. Currently those two pages utilize the files from `single-cell-infra` folder [here](https://github.com/chanzuckerberg/single-cell-infra/tree/main/terraform/modules/hosted-cellxgene/common/customize/deploy), we need to use them in DP now either via Gatsby static pages or just add them as new routes in `frontend/src/components/AppContainer/index.tsx` and do client side rendering

1. Update both cellxgene Explorer and Data Portal links to use the new Data Portal links

1. If we use Gatsby static pages, we'll probably need to update `frontend/gatsby-node.js` to route path `/tos` and `/privacy` to their corresponding new static pages as well

1. Set up Datadog to assert both pages are working in staging and prod

Thank you!

*** TEAM NOTES ***
1. 🎯 Let's try to get the fix out for staging and prod this week!

### PR DESCRIPTION
**Pull request by tihuan**
Fix #747 

Changes:
1. Add Privacy and ToS static pages in Data Portal
1. Update Data Portal links to use the the new URLs

TODO:
1. Need to remove static pages and assets from `single-cell-infra` repo: [PR](https://github.com/chanzuckerberg/single-cell-infra/pull/239)
1. Need to update Explorer to use the new DP URLs: [PR](https://github.com/chanzuckerberg/single-cell-infra/pull/239)
1. Need to add Datadog check

PTAL Thank you 😄 🎉 

Privacy Page:
Screen Shot 2020-12-01 at 9 08 33 PM

ToS Page:
Screen Shot 2020-12-01 at 9 08 46 PM

GIF:
demo

### CODE REVIEW

**Comment by seve** [comment]
Maybe in the future we can disable new account creation if the datadog ping fails? Not sure the importance of these pages, trust-wise

**Comment by tihuan** [comment]
yeah the legality part of this is certainly interesting lol

ACTUALLY! Now the pages are in DP, I can write some quick e2e for them 😄 ! BRB!

**Review by seve — APPROVED** [review]
LGTM

**Comment by tihuan** [comment]
Just added tests too! Thanks all 😄 🎉

**Comment by seve** [comment]
Maybe in the future we can disable new account creation if the datadog ping fails? Not sure the importance of these pages, trust-wise

**Comment by tihuan** [comment]
Hmm yeah that's a great question!

@brianraymor what do you think? Thank you!

**Comment by brianraymor** [comment]
I think our portal should be less fragile so we do not need to add a design to disable features.

**Comment by tihuan** [comment]
@ambrosejcarr @signechambers1 Please help QA this one 🙏

https://cellxgene.dev.single-cell.czi.technology/privacy/
https://cellxgene.dev.single-cell.czi.technology/tos/

cellxgene Explorer has not been updated yet, since the PR is not merged yet!

https://github.com/chanzuckerberg/single-cell-infra/pull/239

**Comment by tihuan** [comment]
@brianraymor Yeah that makes sense 👌 We now have both e2e tests and daily Datadog test (thanks to Madison!) to assert these two pages, so this should be enough! Thank you!

**Pull request merged**
