### PR TITLE
Adding db_access.py script

### PR DESCRIPTION
**Pull request by Bento007**

### CODE REVIEW

**Comment by brianraymor** [comment]
@Bento007 and @tihuan - what's issue is this PR for? Please connect or create as needed.

**Comment by tihuan** [comment]
Ah @Bento007 this seems to be a stale PR. What should we do with this?

And can you help answer @brianraymor 's question above please 😄 🙏 ? Thank you!

**Comment by mckinsel** [comment]
Not stale! Trying to get it to work (problems are unrelated to the PR itself).

This is a prerequisite for #508

**Comment by tihuan** [comment]
Ooh! Sorry for misinterpreting it 😆🙏 Is this the assume role thing that's not working in Docker container?

**Comment by brianraymor** [comment]
@mckinsel - is this still in progress?

**Comment by mckinsel** [comment]
Nope, not sure if we want to merge or just close though. I had asked for an example of a little python code to access the db, and this worked.

**Pull request closed without merging**
