### PR TITLE
fix import

### PR DESCRIPTION
**Pull request by Bento007**

### CODE REVIEW

**Review by MDunitz — APPROVED** [review]
lgtm -- do you need to update the reqs file?

**Comment by Bento007** [comment]
no, `re` is python standard. Our test environment was picking up regex from another package.

**Comment by Bento007** [comment]
the happy path work will help prevent this in the future.

**Comment by Bento007** [comment]
**Cause:** `regex` exists in the requirements needed by the development environment, but does not exist in the requirements for the python lambda environment.

This bug made it through both local testing and the github test environment. Why? Because both of those environments included additional python packages that are not installed on the deployed lambda. These are the packages installed by [requirements.txt](https://github.com/chanzuckerberg/corpora-data-portal/blob/main/requirements.txt) which are needed for development.

In the future, the lambda will be containerized and only contain the minimum required packages. This would have caught the fact that the package that caused the error does not exist in the current python environment.

**Pull request merged**
